version: '3.6'

services:

  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=izanami
      - POSTGRES_USER=izanami
      - POSTGRES_PASSWORD=izanami
    volumes:
      - ./db-datadir:/var/lib/postgresql/data

  web:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
