# Generated by Django 2.1.2 on 2020-02-26 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MAssert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assertCd', models.CharField(max_length=30, verbose_name='資産コード')),
                ('assertNm', models.CharField(max_length=60, verbose_name='資産名')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=6)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='MBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerCd', models.CharField(max_length=30, verbose_name='購入者コード')),
                ('buyerNm', models.CharField(max_length=60, verbose_name='購入者名')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=6)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TShiharaiH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=30, verbose_name='利用者コード')),
                ('usedDate', models.DateField(verbose_name='利用日')),
                ('shopName', models.CharField(max_length=30, verbose_name='店名')),
                ('asseerCd', models.CharField(max_length=30, verbose_name='資産名コード')),
                ('usedAmt', models.IntegerField(verbose_name='利用金額')),
                ('receipt', models.ImageField(max_length=30, upload_to='', verbose_name='レシート')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=6)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TShiharaiM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=30, verbose_name='利用者コード')),
                ('usedDate', models.DateField(verbose_name='利用日')),
                ('shopName', models.CharField(max_length=30, verbose_name='店名')),
                ('asseerCd', models.CharField(max_length=30, verbose_name='資産名コード')),
                ('itemNm', models.CharField(max_length=30, verbose_name='品名')),
                ('buyerCd', models.CharField(max_length=30, verbose_name='購入者コード')),
                ('sumUserAmt', models.IntegerField(verbose_name='金額')),
                ('refundBalance', models.IntegerField(verbose_name='返金残高')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=6)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
