# Generated by Django 2.1.2 on 2020-02-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massert',
            name='user_id',
            field=models.CharField(default=999, max_length=30, verbose_name='利用者コード'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mbuyer',
            name='user_id',
            field=models.CharField(default='a', max_length=30, verbose_name='利用者コード'),
            preserve_default=False,
        ),
    ]
