# Generated by Django 2.1.2 on 2020-02-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0002_auto_20200227_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massert',
            name='assertCd',
        ),
    ]
