# Generated by Django 2.1.2 on 2020-03-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0003_remove_massert_assertcd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbuyer',
            name='buyerCd',
        ),
    ]
