# Generated by Django 2.1.2 on 2020-03-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0004_remove_mbuyer_buyercd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tshiharaih',
            old_name='asseerCd',
            new_name='asseer_cd',
        ),
        migrations.RenameField(
            model_name='tshiharaih',
            old_name='shopName',
            new_name='shop_name',
        ),
        migrations.RenameField(
            model_name='tshiharaih',
            old_name='usedAmt',
            new_name='used_amt',
        ),
        migrations.RenameField(
            model_name='tshiharaih',
            old_name='usedDate',
            new_name='used_date',
        ),
        migrations.RenameField(
            model_name='tshiharaih',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='tshiharaim',
            old_name='asseerCd',
            new_name='asseer_cd',
        ),
        migrations.RenameField(
            model_name='tshiharaim',
            old_name='buyerCd',
            new_name='buyer_cd',
        ),
        migrations.RenameField(
            model_name='tshiharaim',
            old_name='itemNm',
            new_name='item_nm',
        ),
        migrations.RenameField(
            model_name='tshiharaim',
            old_name='refundBalance',
            new_name='refund_balance',
        ),
        migrations.RenameField(
            model_name='tshiharaim',
            old_name='shopName',
            new_name='shop_name',
        ),
        migrations.RenameField(
            model_name='tshiharaim',
            old_name='sumUserAmt',
            new_name='sum_user_amt',
        ),
        migrations.RenameField(
            model_name='tshiharaim',
            old_name='usedDate',
            new_name='used_date',
        ),
        migrations.RenameField(
            model_name='tshiharaim',
            old_name='userId',
            new_name='user_id',
        ),
    ]
