# Generated by Django 2.1.2 on 2020-03-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0005_auto_20200302_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tshiharaih',
            old_name='asseer_cd',
            new_name='assert_cd',
        ),
    ]
