# Generated by Django 2.1.2 on 2020-03-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0006_auto_20200302_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshiharaih',
            name='assert_cd',
            field=models.IntegerField(max_length=30, verbose_name='資産名コード'),
        ),
    ]
