# Generated by Django 2.1.2 on 2020-03-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0007_auto_20200302_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshiharaih',
            name='assert_cd',
            field=models.IntegerField(verbose_name='資産名コード'),
        ),
    ]
