# Generated by Django 2.1.2 on 2020-03-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0009_auto_20200302_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshiharaih',
            name='receipt',
            field=models.ImageField(blank=True, max_length=30, upload_to='', verbose_name='レシート'),
        ),
    ]
