# Generated by Django 2.1.2 on 2020-03-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0010_auto_20200304_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tshiharaim',
            old_name='asseer_cd',
            new_name='assert_cd',
        ),
    ]
