# Generated by Django 2.1.2 on 2020-03-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0011_auto_20200306_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshiharaim',
            name='assert_cd',
            field=models.IntegerField(max_length=30, verbose_name='資産名コード'),
        ),
        migrations.AlterField(
            model_name='tshiharaim',
            name='buyer_cd',
            field=models.IntegerField(max_length=30, verbose_name='購入者コード'),
        ),
        migrations.AlterField(
            model_name='tshiharaim',
            name='user_id',
            field=models.IntegerField(max_length=30, verbose_name='利用者コード'),
        ),
    ]
