# Generated by Django 2.1.2 on 2020-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0013_auto_20200312_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshiharaim',
            name='user_id',
            field=models.CharField(max_length=30, verbose_name='利用者コード'),
        ),
    ]
