# Generated by Django 2.1.2 on 2020-03-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukuyomi', '0014_auto_20200312_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshiharaim',
            name='refund_balance',
            field=models.IntegerField(default=0, verbose_name='返金残高'),
        ),
    ]
