# Generated by Django 2.1.2 on 2020-04-15 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='利用者コード')),
                ('site_name', models.CharField(max_length=100, verbose_name='サイト名')),
                ('login_user_id', models.CharField(max_length=50, verbose_name='ログインID')),
                ('login_user_pw', models.CharField(max_length=50, verbose_name='パスワード')),
                ('site_url', models.CharField(blank=True, max_length=100, verbose_name='サイトURL')),
                ('discription', models.TextField(blank=True, help_text='タスクの詳細な内容を入力して下さい', verbose_name='サイトの詳細')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='登録日時')),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=6)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新日時')),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
