# Generated by Django 2.1.2 on 2020-04-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaterasu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msite',
            name='create_user_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='msite',
            name='update_user_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
