# Generated by Django 2.1.2 on 2020-04-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amaterasu', '0002_auto_20200416_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msite',
            name='discription',
        ),
    ]
