# Generated by Django 2.1.2 on 2020-01-29 06:11

from django.db import migrations, models
import django.utils.timezone
import omoikane.models


class Migration(migrations.Migration):

    dependencies = [
        ('omoikane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='システムにログインするIDを入力してください', max_length=30, verbose_name='ユーザID')),
                ('menu_id', models.CharField(blank=True, max_length=30, verbose_name='メニューID')),
            ],
        ),
        migrations.CreateModel(
            name='MMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField(verbose_name='メニューid')),
                ('menu_name', models.CharField(default='', help_text='システム名を入力してください', max_length=50, verbose_name='システム名称')),
                ('url', models.CharField(default='', help_text='システムのURLを入力してください', max_length=100, verbose_name='URL')),
                ('icon', models.ImageField(upload_to=omoikane.models.get_upload_dir, verbose_name='アイコン')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='登録日時')),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=6)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新日時')),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='muser',
            name='admin_auth',
            field=models.BooleanField(default=False, verbose_name='管理者権限'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='password',
            field=models.CharField(help_text='システムにログインするパスワードを入力してください', max_length=30, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='user_id',
            field=models.CharField(help_text='システムにログインするIDを入力してください', max_length=30, verbose_name='ユーザID'),
        ),
    ]
