# Generated by Django 2.1.2 on 2020-02-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omoikane', '0002_auto_20200129_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmenu',
            name='menu_id',
        ),
        migrations.AlterField(
            model_name='mmenu',
            name='menu_name',
            field=models.CharField(default='', help_text='システム名を入力してください', max_length=50, verbose_name='メニュー名称'),
        ),
    ]
