# Generated by Django 2.1.2 on 2020-02-07 05:42

from django.db import migrations, models
import omoikane.models


class Migration(migrations.Migration):

    dependencies = [
        ('omoikane', '0003_auto_20200206_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmenu',
            name='icon',
            field=models.ImageField(blank=True, upload_to=omoikane.models.get_upload_dir, verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='mmenu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='メニューID'),
        ),
    ]
