# Generated by Django 2.1.2 on 2020-02-10 02:36

from django.db import migrations, models
import omoikane.models


class Migration(migrations.Migration):

    dependencies = [
        ('omoikane', '0006_auto_20200210_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmenu',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=omoikane.models.get_upload_dir, verbose_name='ファイル'),
        ),
    ]
