# Generated by Django 2.1.2 on 2020-04-27 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='利用者コード')),
                ('item_name', models.CharField(max_length=100, verbose_name='場所名')),
                ('safety_amt', models.IntegerField(max_length=100, verbose_name='安全在庫数')),
                ('item_term', models.IntegerField(max_length=100, verbose_name='在庫期間')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='登録日時')),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=30)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新日時')),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MItemPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='利用者コード')),
                ('item_id', models.CharField(max_length=100, verbose_name='品目名')),
                ('place_id', models.CharField(max_length=100, verbose_name='場所')),
                ('item_amt', models.IntegerField(blank=True, max_length=100, verbose_name='在庫数')),
                ('dwonload_date', models.DateTimeField(blank=True, verbose_name='ダウンロード日時')),
                ('upload_date', models.DateTimeField(blank=True, max_length=100, verbose_name='アップロード日時')),
                ('buy_amt', models.IntegerField(blank=True, max_length=100, verbose_name='購入数')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='登録日時')),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=30)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新日時')),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='利用者コード')),
                ('place_name', models.CharField(max_length=100, verbose_name='場所名')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='登録日時')),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=30)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新日時')),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='利用者コード')),
                ('item_id', models.CharField(max_length=100, verbose_name='品目名')),
                ('place_id', models.CharField(max_length=100, verbose_name='場所')),
                ('item_amt', models.IntegerField(blank=True, max_length=100, verbose_name='在庫数')),
                ('dwonload_date', models.DateTimeField(blank=True, verbose_name='ダウンロード日時')),
                ('upload_date', models.DateTimeField(blank=True, max_length=100, verbose_name='アップロード日時')),
                ('buy_amt', models.IntegerField(blank=True, max_length=100, verbose_name='購入数')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='登録日時')),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=30)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新日時')),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
