# Generated by Django 2.1.2 on 2020-04-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenouzume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitem',
            name='item_term',
            field=models.IntegerField(verbose_name='在庫期間'),
        ),
        migrations.AlterField(
            model_name='mitem',
            name='safety_amt',
            field=models.IntegerField(verbose_name='安全在庫数'),
        ),
        migrations.AlterField(
            model_name='mitemplace',
            name='buy_amt',
            field=models.IntegerField(blank=True, verbose_name='購入数'),
        ),
        migrations.AlterField(
            model_name='mitemplace',
            name='item_amt',
            field=models.IntegerField(blank=True, verbose_name='在庫数'),
        ),
        migrations.AlterField(
            model_name='tstock',
            name='buy_amt',
            field=models.IntegerField(blank=True, verbose_name='購入数'),
        ),
        migrations.AlterField(
            model_name='tstock',
            name='item_amt',
            field=models.IntegerField(blank=True, verbose_name='在庫数'),
        ),
    ]
