# Generated by Django 2.1.2 on 2020-04-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenouzume', '0005_auto_20200428_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitem',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='品目名'),
        ),
    ]
