# Generated by Django 2.1.2 on 2020-04-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenouzume', '0006_auto_20200428_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitemplace',
            name='safety_amt',
            field=models.IntegerField(default=0, verbose_name='安全在庫数'),
        ),
    ]
