# Generated by Django 2.1.2 on 2020-04-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenouzume', '0007_mitemplace_safety_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitemplace',
            name='buy_amt',
            field=models.IntegerField(blank=True, default=0, verbose_name='購入数'),
        ),
        migrations.AlterField(
            model_name='mitemplace',
            name='item_amt',
            field=models.IntegerField(blank=True, default=0, verbose_name='在庫数'),
        ),
    ]
