# Generated by Django 2.1.2 on 2020-04-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenouzume', '0008_auto_20200430_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitemplace',
            name='dwonload_date',
        ),
        migrations.RemoveField(
            model_name='mitemplace',
            name='upload_date',
        ),
    ]
