# Generated by Django 2.1.2 on 2020-05-01 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amenouzume', '0009_auto_20200430_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitemplace',
            name='buy_amt',
        ),
        migrations.RemoveField(
            model_name='mitemplace',
            name='item_amt',
        ),
        migrations.RemoveField(
            model_name='mitemplace',
            name='safety_amt',
        ),
        migrations.AddField(
            model_name='tstock',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='品目名'),
        ),
        migrations.AddField(
            model_name='tstock',
            name='safety_amt',
            field=models.IntegerField(default=0, verbose_name='安全在庫数'),
        ),
        migrations.AlterField(
            model_name='tstock',
            name='dwonload_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='ダウンロード日時'),
        ),
        migrations.AlterField(
            model_name='tstock',
            name='item_id',
            field=models.CharField(max_length=100, verbose_name='品目ID'),
        ),
        migrations.AlterField(
            model_name='tstock',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='アップロード日時'),
        ),
    ]
