# Generated by Django 2.1.2 on 2020-09-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenouzume', '0011_auto_20200505_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tstockhistory',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='品目名'),
        ),
        migrations.AddField(
            model_name='tstockhistory',
            name='safety_amt',
            field=models.IntegerField(default=0, verbose_name='安全在庫数'),
        ),
    ]
