# Generated by Django 2.1.2 on 2020-09-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenouzume', '0012_auto_20200914_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tstockhistory',
            old_name='dwonload_date',
            new_name='download_date',
        ),
    ]
