# Generated by Django 2.1.2 on 2019-05-17 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', help_text='システムにログインするIDを入力してください', max_length=30, verbose_name='ユーザID')),
                ('user_name', models.CharField(default='', help_text='お名前を入力してください', max_length=30, verbose_name='ユーザ名')),
                ('password', models.CharField(default='', help_text='システムにログインするパスワードを入力してください', max_length=30, verbose_name='パスワード')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='登録日時')),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=6)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新日時')),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TRemaind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('task_id', models.CharField(max_length=30)),
                ('task_date_time', models.DateTimeField()),
                ('message', models.TextField()),
                ('create_date', models.TimeField()),
                ('create_pg_id', models.CharField(max_length=30)),
                ('create_user_id', models.CharField(max_length=6)),
                ('update_date', models.TimeField()),
                ('update_pg_id', models.CharField(max_length=30)),
                ('update_user_id', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('todo_id', models.CharField(max_length=30)),
                ('task_date_time', models.DateTimeField()),
                ('task_discription', models.TextField()),
                ('create_date', models.TimeField()),
                ('create_pg_id', models.CharField(max_length=30)),
                ('create_user_id', models.CharField(max_length=6)),
                ('update_date', models.TimeField()),
                ('update_pg_id', models.CharField(max_length=30)),
                ('update_user_id', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='タスクのタイトルを入力してください', max_length=30, verbose_name='タイトル')),
                ('discription', models.CharField(help_text='タスクの詳細な内容を入力して下さい', max_length=200, verbose_name='タスクの詳細')),
                ('should_action', models.BooleanField(blank=True, verbose_name='行動を起こす必要があるか？')),
                ('action_selection', models.CharField(blank=True, choices=[('1', 'いつかやる'), ('2', '参考資料'), ('3', 'ごみ箱')], max_length=1)),
                ('single_action', models.BooleanField(blank=True, verbose_name='アクションは１つ？')),
                ('can_do_tow_minite', models.BooleanField(blank=True, verbose_name='２分以内で終わる？')),
                ('should_myself', models.BooleanField(blank=True, verbose_name='自分でやるべき')),
                ('should_do_than_2min', models.BooleanField(blank=True, verbose_name='特定の日にやるべき？')),
                ('user_id', models.CharField(blank=True, max_length=6, verbose_name='ログインID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='登録日時')),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=6)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新日時')),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
