# Generated by Django 2.1.2 on 2019-04-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttodo',
            name='where_dont_action',
        ),
    ]
