# Generated by Django 2.1.2 on 2019-09-16 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0003_auto_20190916_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttodo',
            name='delivery_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='期限'),
        ),
    ]
