# Generated by Django 2.1.2 on 2019-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0004_auto_20190916_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttodo',
            name='completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='完了'),
        ),
    ]
