# Generated by Django 2.1.2 on 2019-10-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0007_auto_20190927_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttodo',
            name='action_selection',
            field=models.CharField(blank=True, choices=[('1', 'いつかやる'), ('2', '参考資料'), ('3', 'ごみ箱')], max_length=1, verbose_name='行動'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='期限'),
        ),
    ]
