# Generated by Django 2.1.2 on 2019-11-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0012_ttodo_request_pertner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttodo',
            name='date_should_do',
            field=models.DateField(blank=True, null=True, verbose_name='実行日'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='action_selection',
            field=models.CharField(blank=True, choices=[('1', 'いつかやる'), ('2', '参考資料'), ('3', 'ごみ箱')], max_length=1, verbose_name='行動しない場合'),
        ),
    ]
