# Generated by Django 2.1.2 on 2019-12-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0014_tshiryou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshiryou',
            name='attach',
            field=models.FileField(upload_to='', verbose_name='添付ファイル'),
        ),
    ]
