# Generated by Django 2.1.2 on 2019-12-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0017_auto_20191218_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MUser',
        ),
    ]
