# Generated by Django 2.1.2 on 2020-01-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0018_delete_muser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TRemaind',
        ),
        migrations.DeleteModel(
            name='TTask',
        ),
    ]
