# Generated by Django 2.1.2 on 2020-09-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.CharField(max_length=30, verbose_name='キー１')),
                ('key2', models.CharField(max_length=30, verbose_name='キー２')),
                ('key3', models.CharField(max_length=30, verbose_name='キー３')),
                ('value1', models.CharField(max_length=30, verbose_name='文字列１')),
                ('value2', models.CharField(max_length=30, verbose_name='文字列２')),
                ('value3', models.CharField(max_length=30, verbose_name='文字列３')),
                ('value4', models.CharField(max_length=30, verbose_name='文字列４')),
                ('value5', models.CharField(max_length=30, verbose_name='文字列５')),
                ('valueNum1', models.IntegerField(max_length=30, verbose_name='数値１')),
                ('valueNum2', models.IntegerField(max_length=30, verbose_name='数値２')),
                ('valueNum3', models.IntegerField(max_length=30, verbose_name='数値３')),
                ('valueNum4', models.IntegerField(max_length=30, verbose_name='数値４')),
                ('valueNum5', models.IntegerField(max_length=30, verbose_name='数値５')),
                ('valueFloat1', models.FloatField(max_length=30, verbose_name='小数１')),
                ('valueFloat2', models.FloatField(max_length=30, verbose_name='小数２')),
                ('valueFloat3', models.FloatField(max_length=30, verbose_name='小数３')),
                ('valueFloat4', models.FloatField(max_length=30, verbose_name='小数４')),
                ('valueFloat5', models.FloatField(max_length=30, verbose_name='小数５')),
            ],
        ),
    ]
