# Generated by Django 2.1.2 on 2020-09-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izanagi', '0002_auto_20200916_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgeneral',
            name='key1',
            field=models.CharField(default='', max_length=30, verbose_name='キー１'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='key2',
            field=models.CharField(default='', max_length=30, verbose_name='キー２'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='key3',
            field=models.CharField(default='', max_length=30, verbose_name='キー３'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='value1',
            field=models.CharField(default='', max_length=30, verbose_name='文字列１'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='value2',
            field=models.CharField(default='', max_length=30, verbose_name='文字列２'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='value3',
            field=models.CharField(default='', max_length=30, verbose_name='文字列３'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='value4',
            field=models.CharField(default='', max_length=30, verbose_name='文字列４'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='value5',
            field=models.CharField(default='', max_length=30, verbose_name='文字列５'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='valueFloat1',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='valueFloat2',
            field=models.FloatField(default=0.0, verbose_name='小数２'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='valueFloat3',
            field=models.FloatField(default=0.0, verbose_name='小数３'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='valueFloat4',
            field=models.FloatField(default=0.0, verbose_name='小数４'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='valueFloat5',
            field=models.FloatField(default=0.0, verbose_name='小数５'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='valueNum1',
            field=models.IntegerField(default=0, verbose_name='数値１'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='valueNum2',
            field=models.IntegerField(default=0, verbose_name='数値２'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='valueNum3',
            field=models.IntegerField(default=0, verbose_name='数値３'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='valueNum4',
            field=models.IntegerField(default=0, verbose_name='数値４'),
        ),
        migrations.AlterField(
            model_name='mgeneral',
            name='valueNum5',
            field=models.IntegerField(default=0, verbose_name='数値５'),
        ),
    ]
