# Generated by Django 2.1.2 on 2019-05-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttodo',
            name='category',
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='discription',
            field=models.CharField(help_text='タスクの詳細な内容を入力して下さい', max_length=200, verbose_name='タスクの詳細'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='title',
            field=models.CharField(help_text='タスクのタイトルを入力してください', max_length=30, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='update_date',
            field=models.TimeField(auto_now_add=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='user_id',
            field=models.CharField(max_length=6, verbose_name='ログインID'),
        ),
    ]
