# Generated by Django 2.1.2 on 2019-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0003_auto_20190507_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttodo',
            name='can_do_tow_minite',
            field=models.BooleanField(default=False, verbose_name='２分以内で終わる？'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='should_do_than_2min',
            field=models.BooleanField(default=False, verbose_name='特定の日にやるべき？'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='should_myself',
            field=models.BooleanField(default=False, verbose_name='自分でやるべき'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='single_action',
            field=models.BooleanField(default=False, verbose_name='アクションは１つ？'),
        ),
    ]
