# Generated by Django 2.1.2 on 2019-05-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0004_auto_20190509_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttodo',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新日時'),
        ),
    ]
