# Generated by Django 2.1.2 on 2019-05-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0005_auto_20190509_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttodo',
            name='action_selection',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='can_do_tow_minite',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='create_pg_id',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='should_action',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='should_do_than_2min',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='should_myself',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='single_action',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='update_pg_id',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='update_user_id',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='user_id',
        ),
    ]
