# Generated by Django 2.1.2 on 2019-05-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0007_ttodo_action_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttodo',
            name='should_action',
            field=models.BooleanField(default=False, verbose_name='行動を起こす必要があるか？'),
        ),
    ]
