# Generated by Django 2.1.2 on 2019-05-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0009_auto_20190516_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttodo',
            name='user_id',
            field=models.CharField(default='', max_length=6, verbose_name='ログインID'),
        ),
    ]
