# Generated by Django 2.1.2 on 2019-05-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0010_ttodo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttodo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AddField(
            model_name='ttodo',
            name='create_pg_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ttodo',
            name='create_user_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='ttodo',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='ttodo',
            name='update_pg_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ttodo',
            name='update_user_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='can_do_tow_minite',
            field=models.BooleanField(default=True, verbose_name='２分以内で終わる？'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='should_action',
            field=models.BooleanField(default=True, verbose_name='行動を起こす必要があるか？'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='should_do_than_2min',
            field=models.BooleanField(default=True, verbose_name='特定の日にやるべき？'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='should_myself',
            field=models.BooleanField(default=True, verbose_name='自分でやるべき'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='single_action',
            field=models.BooleanField(default=True, verbose_name='アクションは１つ？'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='user_id',
            field=models.CharField(default='', max_length=6, null=True, verbose_name='ログインID'),
        ),
    ]
