# Generated by Django 2.1.2 on 2019-05-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0011_auto_20190517_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttodo',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='create_pg_id',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='update_pg_id',
        ),
        migrations.RemoveField(
            model_name='ttodo',
            name='update_user_id',
        ),
    ]
