# Generated by Django 2.1.2 on 2019-05-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0012_auto_20190517_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttodo',
            name='user_id',
            field=models.CharField(max_length=6, verbose_name='ログインID'),
        ),
    ]
