# Generated by Django 2.1.2 on 2019-05-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0015_auto_20190517_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttodo',
            name='create_pg_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ttodo',
            name='create_user_id',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='ttodo',
            name='update_pg_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ttodo',
            name='update_user_id',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
