# Generated by Django 2.1.2 on 2019-05-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0018_auto_20190517_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='password',
            field=models.CharField(help_text='システムにログインするパスワードを入力してください', max_length=30, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='user_id',
            field=models.CharField(help_text='システムにログインするIDを入力してください', max_length=30, verbose_name='ユーザID'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='user_name',
            field=models.CharField(help_text='お名前を入力してください', max_length=30, verbose_name='ユーザ名'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='action_selection',
            field=models.CharField(blank=True, choices=[('1', 'いつかやる'), ('2', '参考資料'), ('3', 'ごみ箱')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='can_do_tow_minite',
            field=models.BooleanField(blank=True, verbose_name='２分以内で終わる？'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='should_action',
            field=models.BooleanField(blank=True, verbose_name='行動を起こす必要があるか？'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='should_do_than_2min',
            field=models.BooleanField(blank=True, verbose_name='特定の日にやるべき？'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='should_myself',
            field=models.BooleanField(blank=True, verbose_name='自分でやるべき'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='single_action',
            field=models.BooleanField(blank=True, verbose_name='アクションは１つ？'),
        ),
    ]
