# Generated by Django 2.1.2 on 2019-05-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0019_auto_20190517_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muser',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='update_date',
        ),
    ]
