# Generated by Django 2.1.2 on 2019-05-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0020_auto_20190517_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muser',
            name='create_pg_id',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='update_pg_id',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='update_user_id',
        ),
    ]
