# Generated by Django 2.1.2 on 2019-05-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0021_auto_20190517_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='muser',
            name='user_name',
        ),
    ]
