# Generated by Django 2.1.2 on 2019-05-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susanowo', '0022_auto_20190517_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='muser',
            name='password',
            field=models.CharField(default='', help_text='システムにログインするパスワードを入力してください', max_length=30, verbose_name='パスワード'),
        ),
        migrations.AddField(
            model_name='muser',
            name='user_name',
            field=models.CharField(default='', help_text='お名前を入力してください', max_length=30, verbose_name='ユーザ名'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='user_id',
            field=models.CharField(default='', help_text='システムにログインするIDを入力してください', max_length=30, verbose_name='ユーザID'),
        ),
    ]
