# Generated by Django 2.1.2 on 2020-11-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarutahiko', '0002_mrecipeitem_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tkondate',
            name='is_noon',
        ),
        migrations.AddField(
            model_name='tkondate',
            name='recipe_id',
            field=models.CharField(default='', max_length=30, verbose_name='レシピID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tkondate',
            name='time',
            field=models.CharField(default='', max_length=1, verbose_name='時間帯'),
            preserve_default=False,
        ),
    ]
